apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zen-messaging-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.zen.serri.in
    secretName: zen-messaging-tls
  rules:
  - host: api.zen.serri.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zen-messaging-gateway
            port:
              number: 80
